ur5_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
  gains:
    ur5_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ur5_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5_bl_to_leftFinger
    - ur5_leftFinger_to_rightFinger
  gains:
    ur5_bl_to_leftFinger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_leftFinger_to_rightFinger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ur5e_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5e_shoulder_pan_joint
    - ur5e_shoulder_lift_joint
    - ur5e_elbow_joint
    - ur5e_wrist_1_joint
    - ur5e_wrist_2_joint
    - ur5e_wrist_3_joint
  gains:
    ur5e_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ur5e_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5e_bl_to_leftFinger
    - ur5e_leftFinger_to_rightFinger
  gains:
    ur5e_bl_to_leftFinger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5e_leftFinger_to_rightFinger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1